### ISSUE TITLE
Beta release: how to add extension boards via i2c

### ISSUE THREAD

**Issue by rudyvan** [UniPiTechnology/evok#118]
Hello,

i have added an EMO R8 relais extension board on hex 21 and a EMO-1w 8 extension board on hex 19, see below the i2cdetect output that shows they are recognised.

<img width="301" alt="image" src="https://github.com/UniPiTechnology/evok/assets/13715940/ce9dc88b-3394-456d-882b-dde6853bab7d">

I assumed they were automatically recognised, i tried a reinstallation of evok and a reboot but unfortunately to no avail.

Should i therefore update a yaml file in /etc/evok? 
The examples in the docs are for modbus or tcp extensions, but not for i2c legacy devices?
How can we add i2c legacy devices?  Please point me in the right direction.

**Comment by miroslav-ondra** [comment]
Look at [https://github.com/UniPiTechnology/unipi-one-modbus](url) how to add EMO R8.
EMO-1w is no more supported but Evok uses owserver. You can add second ow-master chip at 0x19 to config file of owserver.

**Comment by rudyvan** [comment]
Hello,

To add an EMO R8 on address x21, i have followed the steps outlined.
see below, i added overlay in boot.txt, created module_id.1 and run os-configurator and HAS_EMOR8_1='1' emerged.

after reboot, i do not see the extra relays appearing in web-evok, is there something else to do to make them appear?

Thanks!

```
pi@PI-Main:~ $ sudo su
root@PI-Main:/home/pi# echo 0018 > /etc/unipi-id/module_id.1
root@PI-Main:/home/pi# exit
exit
pi@PI-Main:~ $ ls /etc/unipi-id
module_id.1  README.md
pi@PI-Main:~ $ sudo nano /etc/unipi-id/README.md
pi@PI-Main:~ $ sudo /opt/unipi/tools/os-configurator --force
DT='unipi_unipi11 em0018_slot1'
UDEV='unipi_unipi11 em0018_slot1'
HAS_DS2482='1'
HAS_RTC='1'
USE_ETC_MODULES='1'
UNIPI_PLATFORM='0101'
UNIPI_PRODUCT_ID='0101'
UNIPI_PRODUCT_NAME='UNIPI11'
UNIPI_PRODUCT_SERIAL='391708672'
HAS_EMOR8_1='1'
run-parts: executing /opt/unipi/os-configurator/run.d/10-config_txt.sh
run-parts: executing /opt/unipi/os-configurator/run.d/20-overlays.sh
run-parts: executing /opt/unipi/os-configurator/run.d/20-uoverlays.sh
run-parts: executing /opt/unipi/os-configurator/run.d/30-udev.sh
run-parts: executing /opt/unipi/os-configurator/run.d/30-udevvar.sh
run-parts: executing /opt/unipi/os-configurator/run.d/50-configure-one.sh
run-parts: executing /opt/unipi/os-configurator/run.d/50-unipi-hostname.sh
run-parts: executing /opt/unipi/os-configurator/run.d/98-bootcmd.sh
run-parts: executing /opt/unipi/os-configurator/run.d/99-wait-for-resize.sh
run-parts: executing /opt/unipi/os-configurator/run.d/evok-autogen.sh
Detect device UNIPI1 UNIPI11 (id=0x101, sn=391708672) with boards ['UNIPI11']
Reboot system to apply all changes in configuration
pi@PI-Main:~ $ sudo reboot
```

**Comment by rudyvan** [comment]
Hello,

to have the legacy EMO-1w working, one can make the following changes to /etc/owfs.conf:

```
### CONFIGURED BY EVOK ###
server: i2c=/dev/i2c-1
server: w1
##########################
```

change to:

```
### CONFIGURED BY EVOK ###
server: i2c=ALL:ALL
server: w1
##########################
```

and then:

sudo service owserver restart

(just make sure the hex address of added EMO-1w start at x19)

**Comment by rudyvan** [comment]
there seems to be an issue in os-configurator when adding an EMO-R8.

when i run os-configurator, it says that HAS_EMOR8_1='1'

```
DT='unipi_unipi11 em0018_slot1'
UDEV='unipi_unipi11 em0018_slot1'
HAS_DS2482='1'
HAS_RTC='1'
USE_ETC_MODULES='1'
UNIPI_PLATFORM='0101'
UNIPI_PRODUCT_ID='0101'
UNIPI_PRODUCT_NAME='UNIPI11'
UNIPI_PRODUCT_SERIAL='391708672'
HAS_EMOR8_1='1'
run-parts: executing /opt/unipi/os-configurator/run.d/10-config_txt.sh
run-parts: executing /opt/unipi/os-configurator/run.d/20-overlays.sh
run-parts: executing /opt/unipi/os-configurator/run.d/20-uoverlays.sh
run-parts: executing /opt/unipi/os-configurator/run.d/30-udev.sh
run-parts: executing /opt/unipi/os-configurator/run.d/30-udevvar.sh
run-parts: executing /opt/unipi/os-configurator/run.d/50-configure-one.sh
run-parts: executing /opt/unipi/os-configurator/run.d/50-unipi-hostname.sh
run-parts: executing /opt/unipi/os-configurator/run.d/98-bootcmd.sh
run-parts: executing /opt/unipi/os-configurator/run.d/99-wait-for-resize.sh
run-parts: executing /opt/unipi/os-configurator/run.d/evok-autogen.sh
Detect device UNIPI1 UNIPI11 (id=0x101, sn=391708672) with boards ['UNIPI11']
```

however /etc/autogen.yaml has nothing of EMO-R8:

```
omm_channels:
  LOCAL_TCP:
    type: MODBUSTCP
    hostname: 127.0.0.1
    port: 503
    device_info:
      family: UNIPI1
      model: UNIPI11
      sn: 391708672
      board_count: 1
    devices:
      1:
        slave-id: 0
        model: 'UNIPI11'
  OWFS:
    type: OWBUS
    interval: 10
    scan_interval: 60
```

if i manually add the information that i thing should be generated into /etc/autogen.yaml:

```
comm_channels:
  LOCAL_TCP:
    type: MODBUSTCP
    hostname: 127.0.0.1
    port: 503
    device_info:
      family: UNIPI1
      model: UNIPI11
      sn: 391708672
      board_count: 1
    devices:
      1:
        slave-id: 0
        model: 'UNIPI11'
      2:
        slave-id: 0
        model: 'EMO-R8'
  OWFS:
    type: OWBUS
    interval: 10
    scan_interval: 60
```

and i restart evok, then i see the extra relays in evok-web, but they still do not work
any idea, suggestions?

**Comment by miroslav-ondra** [comment]
Change config:
      2:
        slave-id: **1**
        model: 'EMO-R8'

Emo-R8 is sitting on modbus address 1

**Comment by miroslav-ondra** [comment]
Autoconfiguration of EMO-R8 for Evok is still missing :-(

**Comment by rudyvan** [comment]
i updated autogen.yaml as per your instruction.
(did not know what slave-id is for, was not in the documentation)

```
comm_channels:
  LOCAL_TCP:
    type: MODBUSTCP
    hostname: 127.0.0.1
    port: 503
    device_info:
      family: UNIPI1
      model: UNIPI11
      sn: 391708672
      board_count: 2
    devices:
      1:
        slave-id: 0
        model: 'UNIPI11'
      2:
        slave-id: 1
        model: 'EMO-R8'
  OWFS:
    type: OWBUS
    interval: 10
    scan_interval: 60
```

shows ok in evok-web, but changing the relays does not work on the board for some reason.
Might it be that i am on a RPI5?   I did the app update and upgrade first, so i am with the latest unipi-one-modbus version.
