### ISSUE TITLE
Inconsistency in aliases file format and API endoint

### ISSUE THREAD

**Issue by martytriska** [UniPiTechnology/evok#119]
Format of the aliases dictionary in API differs from the one from file /var/lib/evok/alias.yaml:
```
aliases:
  Kitchen:
    circuit: '1_02'
    devtype: 1
  Living_room:
    circuit: '1_01'
    devtype: 1
```
```
aliases:
  Living_room: 
    input_1_01
  Kitchen:
    input_1_02
```
As the whole API works with "circuit" and "device" properties, aliases generally should follow this in both places above.

Moreover, the "alias" word is the name of the property included id almost every API object. IMHO, it should be better to call the management objects "aliases" to be clearer.
