### ISSUE TITLE
Beta version, test concluded and no issues; added ansible script

### ISSUE THREAD

**Issue by rudyvan** [UniPiTechnology/evok#144]
hello,

i have upgraded all 12 unipi's raspberry's in my configuration to the beta version with the lastest bookworm and latest 3.12.2 python script for my application, and...

everything works well and i enjoyed uninterrupted running for a few days now.

For those starting the migration, be aware that the relays/inputs are renamed (f.i. 1 -> 1_01)

just wanted to say thanks to the EVOK support and development TEAM, during beta testing i had a few issues, but always got a swift response which helped me further, and solved some bugs.

unipi with evok is a fine product which i am enjoying a few years now and i never regretted to commit myself to your hardware and software.

Anyway, for those of you who like to work with Ansible to install/maintain installations, as a free help the script that i use to install evok on unipi.   Up to you to tailor to your own environment.

step 15 in the script is something that can be removed when autogen works for EMO R8.

Again Thanks!

```yaml
# Ansible tasks for installing evok on unipi, see github.com/UniPiTechnology/evok

# evok is a REST API for controlling UniPi devices
# evok-web is a web interface for evok
# unipi-os-configurator-data is a package for configuring UniPi devices
# evok-unipi-data is a package for configuring UniPi devices
# unipi-one-modbus is a TCP package for simulating modbus UniPi devices
# unipi-evok is a package for configuring UniPi devices

- name: 1.installing evok - installing evok dependencies
  shell: |
         wget -qO - https://repo.unipi.technology/debian/raspberry-unipi1.sh | bash
  args:
    chdir: "{{ work_dir }}"
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 2 installing evok - add beta evok to apt sources unipi-evok.list
  lineinfile:
    dest: /etc/apt/sources.list.d/unipi.list
    regex: "^.*betaevok.*\n"
    line: "deb https://repo.unipi.technology/debian betaevok:bookworm main unipi1-main unipi1-test test\n"
    state: present
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 3.installing evok - update apt
  apt:
    update_cache: yes
  args:
    force_apt_get: True
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 4.installing evok - apt-get evok and evok-web
  apt:
    name="{{ packages }}"
    state=latest
    update_cache=yes
  args:
    force_apt_get: True
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  vars:
    packages:
      - evok
      - evok-web
      - unipi-os-configurator-data
      - unipi-one-modbus
  tags:
    - sw
    - raspi
    - evok_restart

- name: 5.installing evok - change API port 8080 to 8181 in /etc/evok/config.yaml
  ansible.builtin.replace:
    path: /etc/evok/config.yaml
    regexp: "^.*port: 8080.*\n"
    replace: "  port: 8181\n"
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: "6.installing evok - change API address 127.0.0.1 to {{ ansible_default_ipv4.address }} in /etc/evok/config.yaml"
  ansible.builtin.replace:
    path: /etc/evok/config.yaml
    regexp: "^.*address: 127.0.0.1.*\n"
    replace: "  address: {{ ansible_default_ipv4.address }}\n"
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 7.installing evok - change web port 80 to 8081 in /etc/nginx/sites-enabled/evok
  ansible.builtin.replace:
    path: /etc/nginx/sites-enabled/evok
    regexp: "^.*listen 80 default_server.*\n"
    replace: "        listen 8180 default_server;\n"
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi


- name: 8.installing evok - change API port 8080 to 8181 in /etc/nginx/sites-enabled/evok
  ansible.builtin.replace:
    path: /etc/nginx/sites-enabled/evok
    regexp: "^.*server 127.0.0.1:8080.*\n"
    replace: "        server 127.0.0.1:8181;\n      server {{ ansible_default_ipv4.address }}:8181;\n"
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi


- name: 9.installing evok - restart or start evok service
  ignore_errors: yes
  ansible.builtin.service:
    name: evok
    state: restarted
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - evok_restart
    - raspi
    - sw

- name: 10.installing evok - restart or start evok-web (nginx) service
  ignore_errors: yes
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - evok_restart
    - raspi
    - sw

- name: 11a.installing evok - add support for legacy EMO-1wire
  lineinfile:
    dest: /etc/owfs.conf
    line: "server: i2c=/dev/i2c-1\n"
    state: absent
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 11b.installing evok - add support for legacy EMO-1wire
  lineinfile:
    dest: /etc/owfs.conf
    line: "server: i2c=ALL:ALL\n"
    state: present
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - sw
    - raspi

- name: 12.installing evok - restart one wire server service
  ignore_errors: yes
  ansible.builtin.service:
    name: owserver
    state: restarted
  become: True
  when: "'unipi' in myconfig and myconfig.unipi"
  tags:
    - evok_restart
    - raspi
    - sw

- name: 13.installing evok - extra EMO-R8 board on 0x21, see "/etc/unipi-id/README.md"
  copy:
    src: files/etc/unipi-id/module_id.1
    dest: /etc/unipi-id/module_id.1
  become: True
  when: "'unipi_emo_r8_1' in myconfig and myconfig.unipi_emo_r8_1"
  tags:
    - sw
    - raspi

- name: 14.installing evok - extra EMO-R8 board, start 'os-configurator'
  command: "/opt/unipi/tools/os-configurator --force"
  become: True
  when: "'unipi_emo_r8_1' in myconfig and myconfig.unipi_emo_r8_1"
  tags:
    - sw
    - raspi

- name: 15.installing evok - extra EMO-R8 board, update autogen.yaml as os-configurator bug
  copy:
    src: files/etc/evok/autogen.yaml
    dest: /etc/evok/autogen.yaml
  become: True
  when: "'unipi_emo_r8_1' in myconfig and myconfig.unipi_emo_r8_1"
  tags:
    - sw
    - raspi

```
